Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false
  config.vm.provider "virtualbox"

  $num_vms = 4
  (2..$num_vms).each do |id|
    config.vm.define "kube-node#{id}" do |node|
      node.vm.hostname = "kube-node#{id}"
      node.vm.network :private_network, ip: "10.64.3.#{id}",  auto_config: true
      node.vm.provider :virtualbox do |vb, override|
        vb.name = "kube-node#{id}"
        vb.gui = false
        vb.memory = 2048
        vb.cpus = 1
      end
      config.vm.provision "shell" do |s|
          ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
          s.inline = <<-SHELL
          echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
          echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
          SHELL
      end
    end
  end
end
